### ISSUE TITLE
Flags.IS_FACTORIO is incorrectly true in YAFC

### ISSUE THREAD

**Issue by DaleStan** [lossycrypt/eradicators-library#2]
Maybe, anyway? This is a result of my investigation into ShadowTheAge/yafc#199. I'm hoping you can shed some more light on what is (or isn't) happening here.

The first problem with combining [YAFC](https://github.com/ShadowTheAge/yafc) and eradicators-library seems to be a YAFC bug, but even after working around that, it doesn't load.

If I replace the two calls to `does_file_exist` in shared.lua with `false`, er still fails in this block:
```lua
  if flag.IS_FACTORIO then
    if not _load_stage then _error('Load stage detection failed.') end
```
In my opinion, YAFC should be executing the code in the else block, since YAFC isn't Factorio. I'm not opposed to improving the Factorio emulation, but I couldn't dig my way through all the indirection to figure out what's actually going wrong.

**Comment by lossycrypt** [comment]
Sorry, for the late answer, but i've been out of factorio modding for over a year. All my mods are due to be officially deprecated when the extensions is released.

As far as i remember the flags in shared mostly do text parsing of debug calls to figure out some stuff that isn't officially supported by the modding api. I only tested the "non factorio mode" in my own dev environment. It's only meant for testing. If you want to get output identical to how it would be in-game you'd have to pretend to actually be the game.
